version: '3'

networks: 
    bdnet:
        ipam:
            config:
                - subnet: 10.100.0.0/24

services: 
    communication-dhaka:
        build: ./Communication/
        restart: always
        #ports: 
        #    - 6401:6401
        networks: 
            bdnet:
                ipv4_address: 10.100.0.3


    riding-dhaka:
        build: ./Riding/
        restart: always
        depends_on: 
            - communication-dhaka
        environment: 
            - LOCATION=dhaka
        networks: 
            bdnet:
                ipv4_address: 10.100.0.2

    nginx-dhaka:
        build: ./nginx/
        #ports: 
        #    - 8002:8002
        depends_on: 
            - riding-dhaka
            - rating-dhaka
        environment: 
            - API_RIDING=riding-dhaka
            - API_RATING=rating-dhaka
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.7

    rating-dhaka:
        build: ./Rating/
        restart: always
        depends_on: 
            - mymongo
        networks: 
            bdnet:
                ipv4_address: 10.100.0.4

    mymongo:
        image: mongo
        #ports: 
        #    - 27018:27017
        restart: always
        networks: 
            bdnet:
                ipv4_address: 10.100.0.5

    
    communication-chottogram:
        build: ./Communication/
        restart: always
        #ports: 
        #    - 6401:6401
        networks: 
            bdnet:
                ipv4_address: 10.100.0.13


    riding-chottogram:
        build: ./Riding/
        restart: always
        depends_on: 
            - communication-chottogram
        environment: 
            - LOCATION=chottogram
        networks: 
            bdnet:
                ipv4_address: 10.100.0.12

    nginx-chottogram:
        build: ./nginx/
        #ports: 
        #    - 8002:8002
        depends_on: 
            - riding-chottogram
            - rating-dhaka
        environment: 
            - API_RIDING=riding-chottogram
            - API_RATING=rating-dhaka
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.11